[package]
name = 'tinymap'
version = '0.1.0'
authors = ['Kai Schmidt <kaikaliischmidt@gmail.com>']
edition = '2018'

[dependencies]

[dev-dependencies]
eggtimer = '*'
rand = "*"

[features]
default = ['alloc']
alloc = []
